# ワークフロー名
name: line_automation

# UT時刻に合わせた時刻指定(現在はUT21時、つまり日本標準時の6時に動作するように設定しています。)
# 曜日指定には [0, 6] の整数を使います。 0 が日曜日、 6 が土曜日です。
on:
  schedule:
    - cron: '0 21 * * *'

jobs:
  build:
    # Ubuntuの最新版環境内で処理を実行することを指定
    runs-on: ubuntu-latest

    # 実行する処理＆コマンド指定
    steps:
      # リポジトリからチェックアウトして以下の処理を実行していく
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          # pip更新
          python -m pip install --upgrade pip
          # 必要なパッケージインストール
          pip install line-bot-sdk
          pip install requests
          pip install beautifulsoup4
      - name: Run script
        run: |
          # .ファイルの実行
          python line_automation_public.py
